// Updated mock data set of real football players.  Each object contains
// the player's name and a notable European club where they played.  Images
// are omitted (set to null) but can be added later if desired.  This list
// is compiled from the top Ballon d'Or rankings between 1990 and 2023 and
// includes 100 well‑known players who all spent part of their careers at
// European clubs.

module.exports = [
  { name: "Lionel Messi", club: "FC Barcelona", image: null },
  { name: "Cristiano Ronaldo", club: "Real Madrid", image: null },
  { name: "Zinedine Zidane", club: "Real Madrid", image: null },
  { name: "Ronaldo Nazário", club: "Inter Milan", image: null },
  { name: "Ronaldinho", club: "FC Barcelona", image: null },
  { name: "Pele", club: "Santos", image: null },
  { name: "Marco van Basten", club: "AC Milan", image: null },
  { name: "Roberto Baggio", club: "Juventus", image: null },
  { name: "Lothar Matthäus", club: "Inter Milan", image: null },
  { name: "Paolo Maldini", club: "AC Milan", image: null },
  { name: "Lucas Paqueta", club: "AC Milan", image: null },
  { name: "Alan Shearer", club: "Newcastle United", image: null },
  { name: "Michael Owen", club: "Liverpool", image: null },
  { name: "Luís Figo", club: "Real Madrid", image: null },
  { name: "Rivaldo", club: "FC Barcelona", image: null },
  { name: "Kaká", club: "AC Milan", image: null },
  { name: "Andriy Shevchenko", club: "AC Milan", image: null },
  { name: "Fabio Cannavaro", club: "Juventus", image: null },
  { name: "Luka Modrić", club: "Real Madrid", image: null },
  { name: "Thierry Henry", club: "Arsenal", image: null },
  { name: "Xavi Hernández", club: "FC Barcelona", image: null },
  { name: "Andrés Iniesta", club: "FC Barcelona", image: null },
  { name: "Neymar Jr.", club: "Paris Saint‑Germain", image: null },
  { name: "Luis Suárez", club: "FC Barcelona", image: null },
  { name: "Robert Lewandowski", club: "Bayern Munich", image: null },
  { name: "Karim Benzema", club: "Real Madrid", image: null },
  { name: "Virgil van Dijk", club: "Liverpool", image: null },
  { name: "Sadio Mané", club: "Liverpool", image: null },
  { name: "Mohamed Salah", club: "Liverpool", image: null },
  { name: "Kevin De Bruyne", club: "Manchester City", image: null },
  { name: "Kylian Mbappé", club: "Paris Saint‑Germain", image: null },
  { name: "Erling Haaland", club: "Manchester City", image: null },
  { name: "Antoine Griezmann", club: "Atlético Madrid", image: null },
  { name: "Franck Ribéry", club: "Bayern Munich", image: null },
  { name: "Manuel Neuer", club: "Bayern Munich", image: null },
  { name: "Wayne Rooney", club: "Manchester United", image: null },
  { name: "David Beckham", club: "Manchester United", image: null },
  { name: "Ryan Giggs", club: "Manchester United", image: null },
  { name: "Steven Gerrard", club: "Liverpool", image: null },
  { name: "Frank Lampard", club: "Chelsea", image: null },
  { name: "Didier Drogba", club: "Chelsea", image: null },
  { name: "Iker Casillas", club: "Real Madrid", image: null },
  { name: "Gianluigi Buffon", club: "Juventus", image: null },
  { name: "Petr Čech", club: "Chelsea", image: null },
  { name: "Alessandro Del Piero", club: "Juventus", image: null },
  { name: "Francesco Totti", club: "AS Roma", image: null },
  { name: "Gabriel Batistuta", club: "Fiorentina", image: null },
  { name: "Enzo Fernandez", club: "Chelsea", image: null },
  { name: "Hristo Stoichkov", club: "FC Barcelona", image: null },
  { name: "Gheorghe Hagi", club: "Real Madrid", image: null },
  { name: "Ruud Gullit", club: "AC Milan", image: null },
  { name: "Yaya Touré", club: "Manchester City", image: null },
  { name: "Samuel Eto'o", club: "FC Barcelona", image: null },
  { name: "Claude Makélélé", club: "Real Madrid", image: null },
  { name: "Sergio Ramos", club: "Real Madrid", image: null },
  { name: "Gerard Piqué", club: "FC Barcelona", image: null },
  { name: "Marcelo", club: "Real Madrid", image: null },
  { name: "Dani Alves", club: "FC Barcelona", image: null },
  { name: "Roberto Carlos", club: "Real Madrid", image: null },
  { name: "Oliver Kahn", club: "Bayern Munich", image: null },
  { name: "Peter Schmeichel", club: "Manchester United", image: null },
  { name: "Clarence Seedorf", club: "AC Milan", image: null },
  { name: "Cesc Fàbregas", club: "Arsenal", image: null },
  { name: "Xabi Alonso", club: "Liverpool", image: null },
  { name: "Wesley Sneijder", club: "Inter Milan", image: null },
  { name: "Miroslav Klose", club: "Bayern Munich", image: null },
  { name: "Michael Ballack", club: "Bayern Munich", image: null },
  { name: "David Villa", club: "FC Barcelona", image: null },
  { name: "Fernando Torres", club: "Liverpool", image: null },
  { name: "Nemanja Vidić", club: "Manchester United", image: null },
  { name: "John Terry", club: "Chelsea", image: null },
  { name: "Raúl González", club: "Real Madrid", image: null },
  { name: "Thomas Muller", club: "Bayern Munich", image: null },
  { name: "Pavel Nedvěd", club: "Juventus", image: null },
  { name: "Deco", club: "FC Barcelona", image: null },
  { name: "Zlatan Ibrahimović", club: "AC Milan", image: null },
  { name: "Sergio Aguero", club: "Manchester City", image: null },
  { name: "Fernando Gago", club: "Boca Juniors", image: null },
  { name: "Carlos Tévez", club: "Juventus", image: null },
  { name: "Juan Sebastián Verón", club: "Lazio", image: null },
  { name: "Bastian Schweinsteiger", club: "Bayern Munich", image: null },
  { name: "Patrick Vieira", club: "Arsenal", image: null },
  { name: "Dennis Bergkamp", club: "Arsenal", image: null },
  { name: "Robin van Persie", club: "Arsenal", image: null },
  { name: "Arjen Robben", club: "Bayern Munich", image: null },
  { name: "Gareth Bale", club: "Real Madrid", image: null },
  { name: "Diego Maradona", club: "Napoli", image: null },
  { name: "Gonzalo Higuain", club: "AC Milan", image: null },
  { name: "Hernán Crespo", club: "Lazio", image: null },
  { name: "Fernando Redondo", club: "Real Madrid", image: null },
  { name: "Martin Palermo", club: "Boca Juniors", image: null },
  { name: "Ariel Ortega", club: "River Plate", image: null },
  { name: "Edgar Davids", club: "Juventus", image: null },
  { name: "Lilian Thuram", club: "Parma", image: null },
  { name: "Rui Costa", club: "AC Milan", image: null },
  { name: "Roman Riquelme", club: "Boca Juniors", image: null },
  { name: "Didier Deschamps", club: "Juventus", image: null },
  { name: "Paul Scholes", club: "Manchester United", image: null },
  { name: "Philipp Lahm", club: "Bayern Munich", image: null },
  { name: "Jay‑Jay Okocha", club: "Paris Saint‑Germain", image: null },
];